version: "3.7"

services:
  app:
    image: node:latest
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 3000:3000
    working_dir: /dw1-lab4
    volumes:
      - ./:/schedules-app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: schedules

  mysql:
    image: mysql:5.7
    volumes:
      - dw1-lab4_mysql:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: schedules

volumes:
  dw1-lab4_mysql: